### PR TITLE
Properly pass PKG_CONFIG_PATH to msys2 shell

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@mwrock @btm @jkeiser

**Comment by mwrock** [comment]
I'm :+1: if we have a green windows build with this all set

**Comment by ksubrama** [comment]
Well - locally I do.  Can't test on Jenkins until a CCR :)

**Comment by mwrock** [comment]
ok I'm good with that

**Pull request merged**
